name: dbti_attendance_system
description: A Flutter project for DBTI Attendance System (Supabase backend).
publish_to: "none" # Prevent publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # PDF / Printing / CSV / Excel
  pdf: ^3.11.0
  printing: ^5.12.0
  csv: ^6.0.0
  excel: ^4.0.3

  # Supabase Flutter SDK
  supabase_flutter: ^2.5.6

  # State management
  provider: ^6.0.5

  # For JSON parsing / models
  http: ^1.2.1

  # For date/time formatting
  intl: ^0.20.2

  # For secure local storage (tokens, PIN)
  shared_preferences: ^2.2.2

  # For PIN input UI
  pinput: ^5.0.2

  # UI helpers
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/dbti_logo.png
